### PR TITLE
feat: Support usergroups.users.list API

### PR DESCRIPTION
**Pull request by doodot**
This pull request adds support for https://api.slack.com/methods/usergroups.users.list

### CODE REVIEW

**Comment by doodot** [comment]
Check was failed due to [derive_partial_eq_without_eq](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq) of model structs.

**Comment by abdolence** [comment]
Hey, thanks for the contributions and sorry for the delay!

**Review by abdolence — APPROVED** [review]
LGTM

**Comment by abdolence** [comment]
Released in v1.2.1.
Also fixed the new Eq/PartialEq clippy warning

**Comment by abdolence** [comment]
@doodot 
The method descriptions declares this method requires the parameter provided:
> usergroup

However I'm not seeing it in your change.
Did it work for you without it?

**Comment by doodot** [comment]
@abdolence 
I didn't recognize that. I added this api as a mock in my project. Sorry for wrong implementation. I will make another pr for this.

**Pull request merged**
