### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by da-x**

### CODE REVIEW

**Comment by abdolence** [comment]
Hey, good findings/suggestions 🏆 
Those error Displays probably I forgot to use `{:?}` for debugging output there, sorry about that.

There are different things blocking me to use your changes directly into master here:
- `client` module shouldn't have a dependency on Tokio since there are people who use other frameworks (already). So let me think about how I can optimise that place relocating some stuff around and changing the internal API.
- There are some type-safety improvements

**Comment by abdolence** [comment]
Extracted the debug messages fix into a separate PR first:
https://github.com/abdolence/slack-morphism-rust/pull/78
Then I'll make some changes related to Tokio/client in another one.

**Comment by abdolence** [comment]
Auth.test implementation in a separate file and with better types:
https://github.com/abdolence/slack-morphism-rust/pull/79

**Comment by abdolence** [comment]
Tokio/threading related optimizations will be fixed in https://github.com/abdolence/slack-morphism-rust/pull/80. So, I'm closing this PR for now. Thanks for your commits, I'll use many of them in various places.

**Comment by abdolence** [comment]
Released all changes in v0.20.0

**Comment by da-x** [comment]
Thanks for working on this @abdolence!

Updating that I tried to rebase on v0.20.0 - the only side effect I see from recent changes in `master` is that after doing Ctrl-C the process waits for 10 seconds before exiting. Logs suggest it takes 10 seconds to shutdown the WS connections. Is this behavior expected/desired?

**Comment by abdolence** [comment]
@da-x This is expected for now with the default Socket Mode configuration (I would expect 5 seconds though, not 10 🤔 ).  There is a connection initial backoff delay for multiple connections for Socket Modes. If this delay is critical for you can manage it setting `initial_backoff_in_seconds` to 0. That place isn't flexible enough for now, so ramping up connections just awaiting some delay there.

**Comment by abdolence** [comment]
Also made some adjustments so we don't wait too much if you have many connections/tokens:
https://github.com/abdolence/slack-morphism-rust/commit/affc60c2c1182d6d1efc2134bb7452ee0aacd0ae

This is not removing that behaviour, more like mitigating a bit.

**Comment by abdolence** [comment]
> process waits for 10 seconds before exiting. 
This shouldn't be an issue now with v0.21.0

**Pull request closed without merging**
